### ISSUE TITLE
Don't unnecessarily cancel spot instance requests

### ISSUE THREAD

**Issue by freshstrangemusic** [jonhoo/tsunami#11]
The default type of spot instance request is [one-time](https://rusoto.github.io/rusoto/rusoto_ec2/struct.RequestSpotInstancesRequest.html#structfield.type_), which means that you shouldnt need to cancel it once it was created -- it will only be fulfilled once.

**Comment by jonhoo** [comment]
Oh, yeah, that's a good point! I'd completely missed that parameter. Want to file a pull request to remove the spot request canceling code?
