### ISSUE TITLE
Use `Path::display()` to display a path

### ISSUE THREAD

**Issue by abusch** [jonhoo/tsunami#14]
I'm just watching part 2 of the video where you add logging, and noticed you log a path in debug format because `Path` doesn't implement `Display`. The reason is that most OSes make no guarantee that a path contains valid UTF8 characters. But you can use `path.display()` to convert it to a displayable value. This is super-minor, but thought I'd mention it :)

The videos are great by the way and super informative :+1:

**Comment by jonhoo** [comment]
Good point -- fixed! I did know about the UTF-8 issue, though I also know there's been some discussion about whether it's worth the inconvenience of not having `impl Display for Path`. Some have also suggested changes that make this more discoverable (https://github.com/rust-lang/rust/issues/38997).
