### ISSUE TITLE
Provide access to standard error output

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tsunami#15]
Currently, the crate only exposes the stdout of a process through [`Session::cmd`](https://docs.rs/tsunami/0.5.10/tsunami/struct.Session.html#method.cmd). However, it'd be nice to also have some other mechanism for easily getting *both* `STDOUT` and `STDERR`. The way to do this would probably be to have a builder of some sort for a command where the user can explicitly say what they want to happen to standard out and to standard error.

**Comment by znewman01** [comment]
IMO this will resolved by #23 (`sessh::Session::cmd` returns a `Result<(String, String), Error>` with both STDOUT/STDERR).

**Comment by jonhoo** [comment]
This is fixed with our move to [`openssh`](https://github.com/jonhoo/openssh), since users can now choose for themselves how to run commands (including capturing output).
