### ISSUE TITLE
Separate run_as into many smaller components

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tsunami#19]
Currently, `run_as` is quite long, and has many relatively independent pieces to it (see also [this comment](https://www.youtube.com/watch?v=1qv1L8t2-W0&lc=UgwDf-qonMNykWUC68V4AaABAg)). Especially on the `async` branch. Splitting that function into many smaller ones would make the code much easier to read and manage! It shouldn't be *too* bad to take most of the closures and split them out into separate private `&self` functions on `TsunamiBuilder`, so we should probably do that!

**Comment by ViktorHavrysh** [comment]
Hey, I've taken a stab at implementing this. Can you take a look please?

**Comment by jonhoo** [comment]
Fixed in #20!
