### ISSUE TITLE
Bring back cleanup code

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tsunami#2]
Code has been written for cleaning up the security group and keypair generated by `tsunami` for every run, but it is currently commented out:

https://github.com/jonhoo/tsunami/blob/379acb77aa8b71a4c92d91342ce76d8a9572e26e/src/lib.rs#L445-L458

This is because it turns out that EC2 won't let you delete resources that are associated with instances that have not yet been terminated. We ran into this during the live-coding session @
https://youtu.be/66INYb73yXo?t=5716. The problem is specifically that although we send a termination request for all the instances, they may not yet have terminated by the time we try to do cleanup (and the deletion of the security group thus fails). The way around this would be to keep checking on all the instances until they have *all* been terminated, and only *then* do cleanup.

**Comment by akshayknarayan** [comment]
I can add this retry loop :)

**Comment by jonhoo** [comment]
That'd be awesome, thanks!
