### ISSUE TITLE
Add support for on-demand AWS instance

### ISSUE THREAD

**Issue by znewman01** [jonhoo/tsunami#25]
I have a horrible hacky implementation on #23: https://github.com/znewman01/tsunami/commit/8c91e80513f6c587621d2ac30a88e8ed046e2430

Which I can clean up (at some point)

**Comment by jonhoo** [comment]
@znewman01 Heads up that I added this in https://github.com/jonhoo/tsunami/pull/45. A quick review would be helpful when you get a chance!

**Comment by znewman01** [comment]
Awesome :)

Will take a look today-ish
