### ISSUE TITLE
Enable user to supply region and credentials provider

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tsunami#3]
At the moment we hard-code the credentials provider and instance region

https://github.com/jonhoo/tsunami/blob/379acb77aa8b71a4c92d91342ce76d8a9572e26e/src/lib.rs#L249-L250

While that makes it easy to get up and running, some users may need to authenticate through more elaborate means (e.g., through `sts::AssumeRole`) as discussed [here](https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md). Similarly, not all users will want to use the US-EAST-1 region for obvious reasons. We should provide a way for the user to specify these options in the builder, perhaps also including the [connector](https://github.com/jonhoo/tsunami/blob/379acb77aa8b71a4c92d91342ce76d8a9572e26e/src/lib.rs#L248) to use.

**Comment by jonhoo** [comment]
cc @Cosaquee

**Comment by matthewkmayer** [comment]
Once https://github.com/rusoto/rusoto/issues/957 is implemented in Rusoto, it should be easier to hand-wave away any hardcoding of regions by using a default region lookup like other AWS SDKs provide. 👍
