### ISSUE TITLE
Increase ssh session timeout

### ISSUE THREAD

**Issue by vitorenesduarte** [jonhoo/tsunami#37]
I have something similar to the ping example where every region is continuously pinging every other region for 30 minutes (with `ping -w 1800`). This experiment failed with the error `the connection was terminated` and I can see this string in `./target/debug/deps/libopenssh-9b9063468e4fbdfc.rlib`.

Internet suggests that this was a timeout in ssh which could be prevented by setting the `ServerAliveInterval` ssh option to 0 (it would never timeout in this case). I was going to open a PR in `openssh` to allow configuring  this option (and maybe also`ServerAliveCountMax`) in [`openssh::SessionBuilder`](https://docs.rs/openssh/0.6.1/openssh/struct.SessionBuilder.html) but I believe this is not enough since the session is created internally in `tsunami`. Given that, I'm not sure how to proceed. Do you have ideas? Thanks.

**Comment by jonhoo** [comment]
Hmm, it's a good question. I don't think that's quite how `ServerAliveInterval` works though? As I understand it, `ServerAliveInterval` is how often the client should send keep-alive messages to the server. Setting that to 0 means "never send keep-alives", which doesn't seem like what you want. I believe it is the _server_ that terminates the ssh connection if it is idle for too long, so what you actually want is to set `ServerAliveInterval` to some **non**-zero number to indicate that a keep-alive _should_ be sent.

You could set this in your `.ssh/config`:
```
Host *
    ServerAliveInterval 240
```
And openssh should pick that up just fine. Having it as an option on `openssh::SessionBuilder` seems pretty reasonable too though.

As for how to pass that through to `tsunami`, maybe one thing to do would be to have a version of [`connect_all`](https://docs.rs/tsunami/0.11.0-beta.4/tsunami/trait.Tsunami.html#tymethod.connect_all) that takes a closure that's given a `&mut openssh::SessionBuilder`, and can modify it to set any additional parameters?

**Comment by vitorenesduarte** [comment]
That makes sense, thanks. I'll try to come up with something.

**Comment by vitorenesduarte** [comment]
It turns out that the error `the connection was terminated` is not related with the `ServerAliveInterval`. In fact, I believe this value was already non-zero due to `BatchMode=yes`, which sets it to 300.

In my experiment I had each region pinging every other region simultaneously using the same ssh connection. Then noticed that per region only 10 (instead of 19) of these outgoing pings were succeeding. I believe this is due to the `MaxSessions` setting in `sshd_config` which by default only allows multiplexing 10 sessions per ssh connection.

```
     MaxSessions
             Specifies the maximum number of open shell, login or subsystem (e.g. sftp) sessions per-
             mitted per network connection.  Multiple sessions may be established by clients that sup-
             port connection multiplexing.  Setting MaxSessions to 1 will effectively disable session
             multiplexing, whereas setting it to 0 will prevent all shell, login and subsystem ses-
             sions while still permitting forwarding.  The default is 10.
```


Given this, I have no need for #38 but I don't mind finishing it up. What do you think?

**Comment by jonhoo** [comment]
Huh, interesting. I think we should then close #38, and re-visit if someone finds a use-case where they need it.

`MaxSessions` seems like it would be good to mention in the top-level docs for `openssh` though! Would you mind filing a PR for that?

**Comment by vitorenesduarte** [comment]
> `MaxSessions` seems like it would be good to mention in the top-level docs for `openssh` though! Would you mind filing a PR for that?

Sure, here it is: https://github.com/jonhoo/openssh-rs/pull/13 (not sure if it's the best wording)
