### ISSUE TITLE
Avoid arbitrary SSH timeout

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/tsunami#5]
We currently keep trying to establish an SSH connection to each instance for up to 2 minutes:

https://github.com/jonhoo/tsunami/blob/379acb77aa8b71a4c92d91342ce76d8a9572e26e/src/ssh.rs#L17-L28

This is a pretty arbitrary limit, and EC2 has been known to occasionally have spawn times longer than this. The right thing to do instead is to keep retrying until the instance is no longer marked as `running`. Should that happen, there is no point in continuing to retry. Theoretically there could be an issue with the firewall rules that prevents connection, so we may still want a high eventual timeout (~5 minutes).

**Comment by AlvinKuruvilla** [comment]
Can we close this issue because the code has been refactored and I don't think this issue is applicable anymore?

**Comment by jonhoo** [comment]
Oh, yes, I suppose you're right! :tada:
